apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP # Vai servir apenas internamente
  selector:
    app: redis # Talvez desse para colocar um outro app (outra label) para representar o logger
    # Service tem acesso a todos os deployments aparentemente. Na prática está fazendo matching na label do pod
  ports:
    - name: redis-svc-port
      port: 6379
      targetPort: 6379
    # Precisaria de algum SMR aplicado. Na prática o k8s não replica rm múltiplas portas, mas faz load balancing.
    # Então para mim a solução seria ou ter SMR no cluster, ou usar sidecar. Ou criar um custom k8s controller?

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-server-pod
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
      - name: redis-client-pod
        image: redis

---
